apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frankrodrigo2/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: backend.backend.svc.cluster.local:5000
