apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: mariadb
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(255) NOT NULL,
      cellphone VARCHAR(20) NOT NULL
    );

    INSERT INTO users (username, cellphone) VALUES
    ('John Doe', '1234567890'),
    ('Jane Smith', '9876543210');
