apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mariadb-secret
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mariadb-data
        emptyDir: {} # Ephemeral storage
      - name: init-scripts
        configMap:
          name: mariadb-config
