apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: mariadb
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: ZGIx
  MYSQL_USER: ZGJ1c2VyMQ==
  MYSQL_PASSWORD: ZGJ1c2VyMQ==
