apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-app
  namespace: argocd
spec:
  project: default  # This ensures it uses the default ArgoCD project
  source:
    repoURL: https://github.com/frankrodrigo/CBD3324_Docker.git
    targetRevision: main
    path: k8s/mariadb-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
