apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: frontend
