apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3306
  selector:
    app: mariadb
